project:
  type: website

execute:
  freeze: auto
  message: false
  warning: false

website:
  title: "Quantitative Text Analysis"
  favicon: assets/hex-sticker.png
  site-url: https://lin-380-s24.github.io/
  description: "Course website for LIN 380: Quantitative Text Analysis, Spring 2024"
  navbar:
    right:
      - index.qmd
      - schedule.qmd
      - slides.qmd
      - guides.qmd
      - news.qmd
      - icon: rss
        href: news.xml
    tools:
      - icon: github
        href: https://github.com/lin-380-s24/
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 3
