project:
  type: website

execute:
  freeze: auto
  message: false
  warning: false

website:
  title: "Quantitative Text Analysis"
  favicon: assets/hex-sticker.png
  navbar:
    right:
      - index.qmd
      - schedule.qmd
      - slides.qmd
      - guides.qmd
      - news.qmd
    tools:
      - icon: github
        href: https://github.com/lin-380-s24/
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 3
