---
title: "Conference Announcement: Emory Undergraduate Linguistics Conference 5 (EULC5)"
date: "2024-01-16"
categories: [news, conferences, research]
---

## Emory Undergraduate Linguistics Conference 5 (EULC5)

Emory University's Program in Linguistics is hosting the fifth annual Emory Undergraduate Linguistics Conference (EULC5) virtually. We are inviting undergraduate students and recent B.A./B.S. graduates to submit abstracts from all subfields of linguistics.

Abstract submissions will be considered for poster and oral presentations. When submitting, you may indicate your preference for consideration for one or both types of presentations in the comment box. All abstracts will be reviewed anonymously. You may submit abstracts for projects that are either in progress or have been completed. Please ensure that your abstract is less than 500 words, excluding figures and references.

Deadline for Abstracts: March 15th, 2024 \
Notifications: By March 29th, 2024 \
Conference Date: April 19th, 2024 (One day virtual event)

If you have any questions, please email at `eulc@emory.edu`

Submissions open: Jan. 3, 2024 - March 20, 2024

Abstract review period: March 16, 2024 - March 29, 2024

<https://easyabs.linguistlist.org/conference/EULC5>
